export interface IPatient {
  _id: string ;
  mrn: string;
  notes: string ;
  titleuid: string ;
  firstname: string ;
  lastname: string;
  middlename: string;
  loginid: string;
  password: string;
  registereddate: string;
  genderuid: string;
  dateofbirth: string;
  preflanguid: string;
  maritalstatusuid: string;
  nationalityuid: string;
  isanonymous: string;
  isvip: string;
  religionuid: string;
  raceuid: string;
  isinterpreterreqd: string;
  patienttypeuid: string;
  nationalid: string;
  natidexpirtydate: string;
  address: string;
  area: string;
  city: string;
  state: string;
  country: string;
  zipcode: string;
  workphone: string;
  homephone: string;
  mobilephone: string;
  alternatephone: string;
  emailid: string;
  weburl: string;
  createdby: string;
  createdat: string;
  modifiedby: string;
  statusflag: string;
  orguid: string;
  patientdocuments: string;
  documentuid: string;
}
